name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.12
  - beautifulsoup4>=4.14.3
  - fiona>=1.10.1
  - gdal=3.12.2
  - geopandas=1.1.2
  - numpy=2.4.2
  - pandas=3.0.0
  - pandoc
  - py-spy
  - rasterio=1.5.0
  - requests=2.32.5
  - scipy=1.17.0
  - shapely=2.1.2
