name: pr_check_cross_platform

on:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:

  ########################################
  # UBUNTU JOB
  ########################################
  mom-check-ubuntu:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        job_type: [VIIRS, GFMS, DFO, HWRF]

    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run setup (Linux)
        run: |
          chmod +x first_setup/setup.sh
          ./first_setup/setup.sh

      - name: Run ${{ matrix.job_type }} job (Linux)
        run: |
          source "$(conda info --base)/etc/profile.d/conda.sh"
          conda activate myenv
          python MoM_run.py -j ${{ matrix.job_type }}
        env:
          AUTH_GLOFAS_USER: ${{ secrets.AUTH_GLOFAS_USER }}
          AUTH_GLOFAS_PASSWD: ${{ secrets.AUTH_GLOFAS_PASSWD }}
          AUTH_DFO_TOKEN: ${{ secrets.AUTH_DFO_TOKEN }}


  ########################################
  # WINDOWS JOB
  ########################################
  mom-check-windows:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        job_type: [VIIRS, GFMS, DFO, HWRF]

    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run setup (Windows)
        shell: pwsh
        run: |
          .\first_setup\setup.ps1

      - name: Run ${{ matrix.job_type }} job (Windows)
        shell: pwsh
        run: |
          .\.venv\Scripts\activate
          .\.venv\Scripts\python.exe MoM_run.py -j ${{ matrix.job_type }}
        env:
          AUTH_GLOFAS_USER: ${{ secrets.AUTH_GLOFAS_USER }}
          AUTH_GLOFAS_PASSWD: ${{ secrets.AUTH_GLOFAS_PASSWD }}
          AUTH_DFO_TOKEN: ${{ secrets.AUTH_DFO_TOKEN }}