name: pr_check_ubuntu

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  mom-check:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false # allows to see failures in all jobs
      matrix:
        job_type: [VIIRS, GFMS, DFO, HWRF]

    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Run setup
        run: |
          chmod +x setup.sh
          ./setup.sh

      - name: Run ${{ matrix.job_type }} job
        run: .venv/bin/python MoM_run.py -j ${{ matrix.job_type }}